language: node_js
node_js:
- '8'
before_install:
- cd Server
install:
- npm install
script:
- npm test

notifications:
  slack:
    secure: p1/NtVtDUeaDIPrz4bStS+VuxhcWAp65gNg4fHpjYu0TO5ddM+EcDKrW5GRUelZE/Hgjf7Zc3h+Tz6Y2gs7IrWTB6PO6h6vDEQ5/ViSRRiWFsWdSt28MYsjegITc4Rr5j6TyRdqik2xu2N1yRRsg1i5uVBzFWta5zpF3iawgSWtLt8HjgcMu1ciTN636hNQjA3g7OnqmytIGrplxp8Vh/YDgrBaZbAve77Lp7Y4r1Vw+w4SR/0O9KBgv7iyEQKZegFRhgPuOcG39J+rvNriyYkWDl5RjYU3/V4jO037KuAdjS+fZyU82Th858F9dN5P3alTc3jp3Kea5l8JnEPMObozoThWiiv/czeUU0SU4ZyM9/1B4200up7iEFLFPS1BIR4nefEnY8vYIi8My6vdiUsn0wGxSprk/GC4tHk/VBiFXjbP4hzFXUKsyrbXAg8h4tZ6dEK5nDTQnIf+pjbXpBXg4scG+tIotsNQVhLvVK2O6q1Jg8JnwMDSXxpgbE6gUg7/Ngdei+nYgnLwyjTJcwVq9q9nlMEhgmsYd0bitsstsJYJv9b75LFs+REzzF8O4PX/qXnXRB0XHdy8w7ECVuU5mrMjRDuxeesqR8+vc/WXcSr1O25GLmBC/77KT4U88Zp3UbTl1ho0KptdGRuTt1JeyMdS7k2y4d+yr8y4JyPw=
